# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f6bf7bdbc65dfa15108bee4a8c8c804e0d1faec25b65a15aef553fb6785e09220e31c04773c8a8870a8f3050f33f6c17dfe4880d9c649aeb5ce70fce3a2866

test:
  secret_key_base: 5d27ded5171241802df26d570baa7d122fdf4c1ddc7d9ec623e018804d9125b0b2393566fc9eef39d31566757ae7832762cdb4623df99dc0ea5c6d59ab5eb82a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
